--------------------------------------------------------
--  File created - Monday-augusti-08-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table S_COUNTRY_CODES
--------------------------------------------------------

  CREATE TABLE "HR"."S_COUNTRY_CODES" 
   (	"COUNTRYCODE" VARCHAR2(26 BYTE), 
	"COUNTRYNAME" VARCHAR2(128 BYTE)
   ) ;
REM INSERTING into HR.S_COUNTRY_CODES
SET DEFINE OFF;
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ABW','Aruba');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('AFG','Afghanistan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('AGO','Angola');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ALB','Albania');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('AND','Andorra');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ARB','Arab World');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ARE','United Arab Emirates');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ARG','Argentina');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ARM','Armenia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ASM','American Samoa');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ATG','Antigua and Barbuda');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('AUS','Australia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('AUT','Austria');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('AZE','Azerbaijan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BDI','Burundi');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BEL','Belgium');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BEN','Benin');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BFA','Burkina Faso');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BGD','Bangladesh');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BGR','Bulgaria');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BHR','Bahrain');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BHS','Bahamas, The');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BIH','Bosnia and Herzegovina');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BLR','Belarus');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BLZ','Belize');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BMU','Bermuda');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BOL','Bolivia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BRA','Brazil');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BRB','Barbados');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BRN','Brunei Darussalam');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BTN','Bhutan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('BWA','Botswana');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CAF','Central African Republic');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CAN','Canada');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CEB','Central Europe and the Baltics');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CHE','Switzerland');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CHI','Channel Islands');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CHL','Chile');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CHN','China');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CIV','Cote d''Ivoire');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CMR','Cameroon');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('COD','Congo, Dem. Rep.');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('COG','Congo, Rep.');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('COL','Colombia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('COM','Comoros');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CPV','Cabo Verde');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CRI','Costa Rica');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CSS','Caribbean small states');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CUB','Cuba');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CUW','Curacao');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CYM','Cayman Islands');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CYP','Cyprus');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('CZE','Czech Republic');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('DEU','Germany');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('DJI','Djibouti');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('DMA','Dominica');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('DNK','Denmark');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('DOM','Dominican Republic');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('DZA','Algeria');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('EAP','East Asia & Pacific (developing only)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('EAS','East Asia & Pacific (all income levels)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ECA','Europe & Central Asia (developing only)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ECS','Europe & Central Asia (all income levels)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ECU','Ecuador');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('EGY','Egypt, Arab Rep.');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('EMU','Euro area');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ERI','Eritrea');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ESP','Spain');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('EST','Estonia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ETH','Ethiopia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('EUU','European Union');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('FCS','Fragile and conflict affected situations');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('FIN','Finland');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('FJI','Fiji');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('FRA','France');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('FRO','Faroe Islands');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('FSM','Micronesia, Fed. Sts.');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GAB','Gabon');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GBR','United Kingdom');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GEO','Georgia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GHA','Ghana');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GIN','Guinea');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GMB','Gambia, The');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GNB','Guinea-Bissau');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GNQ','Equatorial Guinea');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GRC','Greece');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GRD','Grenada');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GRL','Greenland');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GTM','Guatemala');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GUM','Guam');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('GUY','Guyana');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('HIC','High income');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('HKG','Hong Kong SAR, China');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('HND','Honduras');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('HPC','Heavily indebted poor countries (HIPC)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('HRV','Croatia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('HTI','Haiti');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('HUN','Hungary');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('IDN','Indonesia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('IMN','Isle of Man');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('IND','India');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('INX','Not classified');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('IRL','Ireland');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('IRN','Iran, Islamic Rep.');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('IRQ','Iraq');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ISL','Iceland');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ISR','Israel');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ITA','Italy');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('JAM','Jamaica');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('JOR','Jordan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('JPN','Japan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('KAZ','Kazakhstan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('KEN','Kenya');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('KGZ','Kyrgyz Republic');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('KHM','Cambodia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('KIR','Kiribati');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('KNA','St. Kitts and Nevis');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('KOR','Korea, Rep.');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('KSV','Kosovo');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('KWT','Kuwait');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LAC','Latin America & Caribbean (developing only)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LAO','Lao PDR');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LBN','Lebanon');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LBR','Liberia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LBY','Libya');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LCA','St. Lucia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LCN','Latin America & Caribbean (all income levels)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LDC','Least developed countries: UN classification');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LIC','Low income');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LIE','Liechtenstein');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LKA','Sri Lanka');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LMC','Lower middle income');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LMY','Low & middle income');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LSO','Lesotho');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LTU','Lithuania');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LUX','Luxembourg');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('LVA','Latvia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MAC','Macao SAR, China');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MAF','St. Martin (French part)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MAR','Morocco');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MCO','Monaco');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MDA','Moldova');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MDG','Madagascar');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MDV','Maldives');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MEA','Middle East & North Africa (all income levels)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MEX','Mexico');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MHL','Marshall Islands');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MIC','Middle income');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MKD','Macedonia, FYR');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MLI','Mali');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MLT','Malta');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MMR','Myanmar');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MNA','Middle East & North Africa (developing only)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MNE','Montenegro');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MNG','Mongolia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MNP','Northern Mariana Islands');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MOZ','Mozambique');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MRT','Mauritania');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MUS','Mauritius');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MWI','Malawi');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('MYS','Malaysia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NAC','North America');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NAM','Namibia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NCL','New Caledonia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NER','Niger');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NGA','Nigeria');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NIC','Nicaragua');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NLD','Netherlands');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NOC','High income: nonOECD');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NOR','Norway');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NPL','Nepal');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('NZL','New Zealand');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('OEC','High income: OECD');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('OED','OECD members');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('OMN','Oman');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('OSS','Other small states');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PAK','Pakistan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PAN','Panama');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PER','Peru');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PHL','Philippines');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PLW','Palau');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PNG','Papua New Guinea');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('POL','Poland');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PRI','Puerto Rico');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PRK','Korea, Dem. PeopleÂ¿s Rep.');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PRT','Portugal');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PRY','Paraguay');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PSE','West Bank and Gaza');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PSS','Pacific island small states');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('PYF','French Polynesia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('QAT','Qatar');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ROU','Romania');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('RUS','Russian Federation');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('RWA','Rwanda');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SAS','South Asia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SAU','Saudi Arabia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SDN','Sudan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SEN','Senegal');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SGP','Singapore');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SLB','Solomon Islands');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SLE','Sierra Leone');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SLV','El Salvador');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SMR','San Marino');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SOM','Somalia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SRB','Serbia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SSA','Sub-Saharan Africa (developing only)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SSD','South Sudan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SSF','Sub-Saharan Africa (all income levels)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SST','Small states');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('STP','Sao Tome and Principe');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SUR','Suriname');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SVK','Slovak Republic');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SVN','Slovenia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SWE','Sweden');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SWZ','Swaziland');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SXM','Sint Maarten (Dutch part)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SYC','Seychelles');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('SYR','Syrian Arab Republic');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TCA','Turks and Caicos Islands');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TCD','Chad');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TGO','Togo');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('THA','Thailand');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TJK','Tajikistan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TKM','Turkmenistan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TLS','Timor-Leste');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TON','Tonga');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TTO','Trinidad and Tobago');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TUN','Tunisia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TUR','Turkey');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TUV','Tuvalu');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('TZA','Tanzania');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('UGA','Uganda');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('UKR','Ukraine');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('UMC','Upper middle income');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('URY','Uruguay');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('USA','United States');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('UZB','Uzbekistan');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('VCT','St. Vincent and the Grenadines');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('VEN','Venezuela, RB');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('VIR','Virgin Islands (U.S.)');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('VNM','Vietnam');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('VUT','Vanuatu');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('WLD','World');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('WSM','Samoa');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('YEM','Yemen, Rep.');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ZAF','South Africa');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ZMB','Zambia');
Insert into HR.S_COUNTRY_CODES (COUNTRYCODE,COUNTRYNAME) values ('ZWE','Zimbabwe');

commit;