OPTIONS (ERRORS=50)
LOAD DATA 
INFILE '/home/uhellstr/github/livecode.jsontest.oracleapex/sql/S_COUNTRY_FLAGS_DATA_TABLE.ldr' "str '{EOL}'"
APPEND
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "REST_DATA"."S_COUNTRY_FLAGS"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"ALPHA2CODE" CHAR (2),
L_0 FILLER char,
"PNGIMAGE" LOBFILE( L_0) TERMINATED BY EOF NULLIF L_0 = 'null')
